name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Rustup
        run: rustup target add aarch64-apple-darwin
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target aarch64-apple-darwin
      - name: Zip
        run: zip -j rippling-cli.macos-arm.zip ./target/aarch64-apple-darwin/release/rippling-cli
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        run: gh release upload ${{ github.event.release.tag_name }} rippling-cli.macos-arm.zip

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Tar
        run: gzip -c ./target/x86_64-unknown-linux-gnu/release/rippling-cli > rippling-cli.linux-x86_64.gz
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        run: gh release upload ${{ github.event.release.tag_name }} rippling-cli.linux-x86_64.gz
